{% set name = "brainglobe-segmentation" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 124cd091cc378d8d4645b533f96ea8a7f8b54640249f84e8720a8aa360c6ce4e

build:
  entry_points:
    - brainglobe-segmentation = brainglobe_segmentation.segment:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
  run:
    - brainglobe-atlasapi >=2.0.4
    - brainglobe-napari-io >=0.3.0
    - brainglobe-utils >=0.6.0
    - napari >=0.4.5
    - numpy
    - pandas
    - python >=3.10
    - qtpy
    - scikit-image
    - scipy
    - tifffile

test:
  imports:
    - brainglobe_segmentation
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/brainglobe-segmentation
  summary: Manual segmentation of 3D brain structures in a common anatomical space
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/brainglobe/brainglobe-segmentation

extra:
  recipe-maintainers:
    - adamltyson
    - alessandrofelder
