{% set name = "brainglobe-segmentation" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/brainglobe-segmentation-{{ version }}.tar.gz
  sha256: 1fb5ec51f68d73ab71125fa833d34008cc68b2572dcddf740ce0d4664ab0a1e0

build:
  entry_points:
    - brainglobe-segmentation = brainglobe_segmentation.segment:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
  run:
    - brainglobe-atlasapi >=2.0.1
    - brainglobe-napari-io >=0.3.0
    - brainglobe-utils >=0.2.7
    - imio
    - napari >=0.4.5
    - numpy
    - pandas
    - python >=3.9
    - qtpy
    - scikit-image
    - scipy
    - tifffile

test:
  imports:
    - brainglobe_segmentation
  commands:
    - pip list
    - pip check
    # - brainglobe-segmentation --help  # This is opening the napari GUI and not closing
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/brainglobe-segmentation
  summary: Manual segmentation of 3D brain structures in a common anatomical space
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/brainglobe/brainglobe-segmentation

extra:
  recipe-maintainers:
    - adamltyson
    - goanpeca
    - jaimergp
    - willGraham01
