{% set python_min = "3.11" %}
{% set name = "brainglobe-segmentation" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b977290ac005ad1f92d357031b796d1c30d6870c81e0c071fd73a843c0c735c8

build:
  entry_points:
    - brainglobe-segmentation = brainglobe_segmentation.segment:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
  run:
    - brainglobe-atlasapi >=2.0.4
    - brainglobe-napari-io >=0.3.0
    - brainglobe-utils >=0.6.0
    - napari >=0.4.5,<0.6.0
    - numpy
    - pandas
    - python >={{ python_min }}
    - qtpy
    - scikit-image
    - scipy
    - tifffile
    - qt-niu

test:
  imports:
    - brainglobe_segmentation
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/brainglobe-segmentation
  summary: Manual segmentation of 3D brain structures in a common anatomical space
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/brainglobe/brainglobe-segmentation

extra:
  recipe-maintainers:
    - adamltyson
    - alessandrofelder
